name: Release

on:
  push:
    tags: [ '**' ]

permissions:
  contents: read

jobs:
  release:
    uses: 9506hqwy/actions/.github/workflows/dotnet-release.yml@main
    permissions:
      contents: write
